remote_theme: just-the-docs/just-the-docs

title: Nar Docs
description: Documentation for Nar

color_scheme: light

search_enabled: true
search.heading_level: 2
search.previews: 3

heading_anchors: true

# Disable table of contents on all pages
defaults:
  - scope:
      path: ""
    values:
      has_toc: false

aux_links:
  "Nar":
    - "https://nar.narambu.com"
  "Report an Issue":
    - "https://github.com/narambu/nardocs/issues"

footer_content: ""

ga_tracking: false

plugins:
  - jekyll-remote-theme
